services:
  - type: web
    name: hexa-discord-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: TMDB_API_KEY
        sync: false 